import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "../../lib/utils";
import { Providers } from "./lib/nextuiProvider";
import toast, { Toaster } from "react-hot-toast";
import Provider from "./lib/auth/sessionProvider";
import "@uploadthing/react/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(`min-h-screen w-screen`, inter.className)}>
        <Provider>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </Provider>
      </body>
    </html>
  );
}
